import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvid from "./providers/sessionProvider";
import ThemeProvid from "./providers/themeProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PostStream",
  description: "Generated by create next app",
};  

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvid>
          <ThemeProvid>
            <ToastContainer position="bottom-center" />
             {children}
          </ThemeProvid>
        </SessionProvid>
      </body>
    </html>
  );
}
